typography_spectrum: 0
color:
  brandColors:
    - '#adc6dd'
    - '#575a4d'
    - '#000000'
    - '#487faf'
    - '#ebf1f7'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75214
analytics:
  google: null
  facebook: null
  twitter: null
name: RevZ3
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Reverso.Z
description: Overtuig(en)d in Vastgoed
purpose: []
