name: RevZ3
favicon: null
layout_spectrum: 0.75214
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#adc6dd'
    - '#575a4d'
    - '#000000'
    - '#487faf'
    - '#ebf1f7'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
