name: RevZ3
favicon: null
layout_spectrum: 0.9646628603804857
typography_spectrum: 0.9702420004177839
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5141337134409696
  lightness: 0.024319335585460067
  saturation: 0.401195460697636
  rhythmicContrast: 0.35569281061179936
purpose: []
